### ISSUE TITLE
hosts file is gone?

### ISSUE THREAD

**Issue by p1r473** [chrisjudk/hosts#18] opened 2022-04-04 02:18 UTC
404 on https://raw.githubusercontent.com/chrisjudk/hosts/master/hosts

**Comment by T145** [comment] 2022-05-11 19:12
Looks like there may be a comeback here.

**Comment by p1r473** [comment] 2022-05-11 19:46
> Looks like there may be a comeback here.

![image](https://user-images.githubusercontent.com/9235633/167933080-bbed9443-f9cb-4e31-b6ec-216b62e28427.png)

**Comment by T145** [comment] 2022-05-11 19:51
I meant judging from the recent README update: not that the issue is presently resolved.

**Comment by chrisjudk** [comment] 2022-05-16 23:12
@p1r473 @T145 Seems I accidentally committed after Windows Defender removed my hosts file. The issue has been fixed in the latest commit!

**Closed as completed by chrisjudk** 2022-05-16 23:12 UTC
Labels: bug, bug fix

**Comment by T145** [comment] 2022-05-17 18:21
And that's why we use Linux. Lol

**Comment by chrisjudk** [comment] 2022-05-29 21:00
@T145 Don't get me wrong, I dislike windows quite a lot but sadly many games are yet to be ported over for use on linux. It's getting better by the day, but still just not quite there. I've gone back to only touching this project from my ubuntu server to avoid having this occur in the future
